name: CI
on:
  pull_request:
  push:
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11
      - name: Cache scalablytyped
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/scalablytyped/
            ~/.ivy2/local/org.scalablytyped/
          key: ${{ runner.os }}-scalablytyped-v0-${{ hashFiles('project/scalablyTyped.sbt') }}-${{ hashFiles('project/Dependencies.scala') }}
          # restore-keys には必ずScalablyTyped.scalaのhashをつける。 ScalablyTypedのバージョンが変わったら必ずキャッシュを新規に作りたい（そうしないと古いバージョンのキャッシュが残り続ける
          restore-keys: |
            ${{ runner.os }}-scalablytyped-v0-${{ hashFiles('project/scalablyTyped.sbt') }}-
      - name: Build and Test
        run: ./sbt-batch reformatCheck test makeSite
